version: 2
jobs:
  build_and_test:
    working_directory: ~/english_words_of_daily_news
    docker:
      - image: circleci/ruby:2.6.4-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run Rspec unit tests
          command: bundle exec rspec

  deploy_if_on_master:
    machine: true
    working_directory: ~/english_words_of_daily_news
    steps:
      - checkout
      - run:
          name: heroku deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master --force

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_and_test
      - deploy_if_on_master:
         requires:
            - build_and_test
         filters:
           branches:
            only: master
